### PR TITLE
Update gelf.go

### PR DESCRIPTION
**Pull request by lintianzhi**
wrong chunkCountInt when length%chunksize == 0

### CODE REVIEW

**Comment by robertkowalski** [comment]
thank you for your contribution! :) 

one minor thing: can you add a test?

**Comment by lintianzhi** [comment]
ok, test is done

**Comment by lintianzhi** [comment]
Is there any other problem? @robertkowalski

**Comment by robertkowalski** [comment]
sorry for the delay! no there is no problem, I was just 14 days on
vacations and also my computer broke!

will merge tomorrow when my machine is repaired.

**Comment by robertkowalski** [comment]
+1 merge it after squashing / rebase :)

**Comment by lintianzhi** [comment]
rebased

**Comment by robertkowalski** [comment]
+1 merge it :)

**Pull request merged**
